#################################################
# Makefile for Image Rotator 
# 2009 (C) Samsung Electronics 
# Author : Jonghun Han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_ROTATOR)	+= s3c_rotator.o

EXTRA_CFLAGS += -Idrivers/media/video

